# Generated by Django 3.2.13 on 2022-04-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, verbose_name='Тип товара')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('shelf_line', models.DateField(max_length=15, verbose_name='Срок годности')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
    ]
