# Generated by Django 3.2.13 on 2022-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220414_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shelf_line',
            field=models.CharField(max_length=10, verbose_name='Срок годности'),
        ),
    ]
