# Generated by Django 3.2.13 on 2022-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_shelf_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(max_length=10, verbose_name='Дата рождения')),
                ('employee_address', models.CharField(max_length=100, verbose_name='Адрес сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('salary', models.IntegerField(max_length=100, verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
