# Generated by Django 3.2.13 on 2022-04-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField(max_length=100, unique=True, verbose_name='Код заказа')),
                ('date_order', models.DateField(verbose_name='Дата заказа')),
                ('employee', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
