# Generated by Django 3.2.13 on 2022-04-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.CharField(max_length=15, unique=True, verbose_name='Код заказа'),
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_list', models.CharField(max_length=15, unique=True, verbose_name='Номер товарной накладной')),
                ('date_expire', models.DateField(verbose_name='Дата окончания срока годности')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('contractor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.contractor', verbose_name='Поставщик')),
                ('employee', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Сотрудник')),
                ('order', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Код заказа')),
                ('product', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товарная накладная',
                'verbose_name_plural': 'Товарные накладные',
            },
        ),
    ]
