# Generated by Django 3.2.13 on 2022-04-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_packinglist_number_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_stoсk_product', models.CharField(max_length=15, verbose_name='Номер товара на складе')),
                ('quantity_product', models.IntegerField(verbose_name='Количество')),
                ('date_expire_product', models.DateField(verbose_name='Дата окончания срока годности')),
                ('number_packing_list', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='app.packinglist', verbose_name='Номер товарной накладной')),
                ('product_contractor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.contractor', verbose_name='Поставщик')),
                ('product_employee', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Сотрудник')),
                ('product_order', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Код заказа')),
                ('product_stock', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар на складе',
                'verbose_name_plural': 'Товары на складе',
            },
        ),
    ]
