# Generated by Django 3.2.13 on 2022-04-28 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_stockproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_giveaway_list', models.CharField(max_length=15, verbose_name='Номер накладной выдачи/списания')),
                ('quantity_product_away', models.IntegerField(verbose_name='Количество')),
                ('date_away', models.DateField(verbose_name='Дата выдачи/списания')),
                ('reason', models.CharField(max_length=250, verbose_name='Причина')),
                ('number_packing_list_away', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='app.packinglist', verbose_name='Номер товарной накладной')),
                ('product_away', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товар')),
                ('product_contractor_away', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.contractor', verbose_name='Поставщик')),
                ('product_employee', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Сотрудник')),
                ('product_order_away', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Код заказа')),
            ],
            options={
                'verbose_name': 'Накладная выдачи/списания',
                'verbose_name_plural': 'Накладные выдачи/списания',
            },
        ),
    ]
