# Generated by Django 3.2.13 on 2022-05-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_giveaway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
