# Generated by Django 3.2.13 on 2022-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.CharField(max_length=15, verbose_name='Код заказа'),
        ),
    ]
