# Generated by Django 3.2.13 on 2022-05-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_number_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='number_stoсk_product',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер товара на складе'),
        ),
    ]
